language: python
env:
  - PYTHON_VERSION=2.7 IPYTHON_KERNEL=python2
  - PYTHON_VERSION=3.6 IPYTHON_KERNEL=python3
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON_VERSION flake8
    - source activate testenv
    - pip install git+https://github.com/paris-saclay-cds/ramp-workflow.git
    - pip install -r requirements.txt
    - python download_data.py
script:
    - flake8 --ignore E501,F812 *.py submissions/*/*.py
    - ramp_test_submission --quick-test
    - ramp_test_submission --submission keras_fcnn --quick-test
notifications:
  email: true
